# [][][][][][][][][][][][][][][][][][][][][]
#  CratesPlus V${project.version} Config
# [][][][][][][][][][][][][][][][][][][][][]
# ------------------------------------------
# There are many placeholders that can now be used withing the config and messages file, placeholders are as followed:
# - %name% - Replaces with the players name, Example: "Notch".
# - %displayname% - Replaces with the players display name, Example: "[Owner] Notch".
# - %uuid% - Replaces with the players UUID.
# - %crate% - The crate types name.
# - %prize% - The name of the winning.
# - %percentage% - Percentage of the winning, useful for "Chance Message".
# - %rand;100;500% - Generates a random number between two numbers, example is between 100 and 500.
# ------------------------------------------
# Don't change the config version!

Config Version: 6

# Checks if an update is available and notifies staff
Update Checks: true
Update Branch: "spigot"

# Uploads anonymous data about your server, used for general statics
Metrics: true

Crates:
  Vote:
    Knockback: 0.5
    Broadcast: false
    Firework: false
    Color: GREEN
    Block: ENDER_CHEST
    Preview: true
    Cooldown: 2
    Hide Percentages: true
    Permission: cratesplus.crate.example # Permissions can be anything, it will check that the player has the permission before opening
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
      Lore:
      - "This is a Vote key!"
      - "This is just some &eTEST&r text!"
    Winnings:
      '1':
        Type: ITEM
        Item Type: IRON_SWORD
        Item Data: 0
        Percentage: 25
        Name: '&6&lSword of Destiny'
        Amount: 1
        Enchantments:
        - DAMAGE_ALL-3
        Lore:
        - "Testing123"
        Flags:
        - "HIDE_ENCHANTS"
      '2':
        Type: ITEM
        Item Type: DIAMOND_SWORD
        Name: NONE
        Item Data: 0
        Percentage: 25
        Amount: 1
        Enchantments:
        - DAMAGE_ALL-5
        - DURABILITY-3
        - FIRE_ASPECT-2
      '3':
        Type: COMMAND
        Item Type: MOB_SPAWNER
        Percentage: 25
        Commands:
        - 'spawner give %name% spider'
        - 'say %name% opened a crate'
        - 'say %name% got a random %rand;100;500%'
        Name: '&e&lSpider Spawner'
        Item Data: 0
        Amount: 1
        Enchantments:
        - DAMAGE_ALL-5
        - DURABILITY-3
        - FIRE_ASPECT-2
      '4':
        Type: ITEM
        Item Type: MONSTER_EGG
        Percentage: 25
        Name: '&e&lCreeper Egg'
        Item Data: 0
        Entity Type: CREEPER
        Amount: 3
  VIP:
    Knockback: 0.5
    Broadcast: false
    Firework: false
    Color: GREEN
    Block: CHEST
    Preview: true
    Permission: cratesplus.crate.vip # Permissions can be anything, it will check that the player has the permission before opening
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
    Hologram Text:
     - 'This crate will have'
     - 'Its own hologram text!'

# Opener which is used by default
Default Opener: BasicGUI

# Default cooldown between opening crates
Default Cooldown: 5

# If true it will stop players without the admin perm breaking crates
Crate Protection: false

# Disable players being allowed to drop keys to other players, putting them in a chest, or even drop them on death
Disable Key Swapping: false

# %crate% can be used to show the crate name
# If a crate has no specific hologram text set, this will be shown
Default Hologram Text:
- "%crate%"
- "Right-Click to Open!"
- "Left-Click to Preview!"